# Change these first
owner: jaswdr # Your GitHub organization or username, where this repository lives
repo: blog_uptime # The name of this repository

sites:
  - name: Blog
    url: https://jaswdr.dev/
    maxResponseTime: 300

status-website: # Status website (optional)
  baseUrl: /blog_uptime # Custom domain CNAME
  name: Upptime # Status website title
      
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
